name: Cucumber BDD Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cucumber-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Cucumber BDD tests
      run: npm run test:bdd
    
    - name: Upload Cucumber reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cucumber-report
        path: cucumber-report.html